# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 1.1
  - 1.2
  - nightly

matrix:
   allow_failures:
     - julia: nightly

notifications:
  email: false

after_success:
# build documentation
  - julia -e 'cd(Pkg.dir("IntervalContractors")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
# push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("IntervalContractors")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
